# Generated by Django 3.2.16 on 2023-01-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mtaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kata')),
            ],
        ),
        migrations.AddField(
            model_name='kata',
            name='wilaya_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.wilaya'),
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100, unique=True)),
                ('lastname', models.CharField(max_length=100, unique=True)),
                ('kata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kata')),
                ('mtaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.mtaa')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.wilaya')),
            ],
        ),
    ]
