# Generated by Django 3.2.16 on 2023-01-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='node',
            new_name='nida',
        ),
    ]
